-- Generated by scripts/export-supabase-seed.mjs

-- This file replays local Access data into the Supabase-backed tables.

begin;

insert into public.memact_apps (
  id, owner_user_id, name, slug, description, redirect_urls, default_scopes, created_at, updated_at, revoked_at
)
values (
  '5cf04c46-0bd2-4678-ad24-c66016ee8b2f'::uuid,
  (select id from auth.users where lower(email) = lower('thrifthunt3@gmail.com') limit 1),
  'My Memact App',
  'my-memact-app',
  'Uses Memact to form useful schema memory.',
  '[]'::jsonb,
  array['capture:webpage', 'schema:write', 'graph:write', 'memory:write', 'memory:read_summary']::text[],
  '2026-05-06T04:38:04.210Z'::timestamptz,
  '2026-05-06T04:38:04.210Z'::timestamptz,
  null
)
on conflict (id) do update
set
  name = excluded.name,
  slug = excluded.slug,
  description = excluded.description,
  redirect_urls = excluded.redirect_urls,
  default_scopes = excluded.default_scopes,
  updated_at = excluded.updated_at,
  revoked_at = excluded.revoked_at;

insert into public.memact_apps (
  id, owner_user_id, name, slug, description, redirect_urls, default_scopes, created_at, updated_at, revoked_at
)
values (
  '1068dcc9-dcc9-4884-a88d-7e5d7c569b35'::uuid,
  (select id from auth.users where lower(email) = lower('thrifthunt3@gmail.com') limit 1),
  'My Memact App 2',
  'my-memact-app-2',
  'Uses Memact to form useful schema memory.',
  '[]'::jsonb,
  array['capture:webpage', 'schema:write', 'graph:write', 'memory:write', 'memory:read_summary']::text[],
  '2026-05-06T07:39:22.047Z'::timestamptz,
  '2026-05-06T07:39:22.049Z'::timestamptz,
  null
)
on conflict (id) do update
set
  name = excluded.name,
  slug = excluded.slug,
  description = excluded.description,
  redirect_urls = excluded.redirect_urls,
  default_scopes = excluded.default_scopes,
  updated_at = excluded.updated_at,
  revoked_at = excluded.revoked_at;

insert into public.memact_apps (
  id, owner_user_id, name, slug, description, redirect_urls, default_scopes, created_at, updated_at, revoked_at
)
values (
  '7e2c3735-3e44-4e25-be86-23d06d15884d'::uuid,
  (select id from auth.users where lower(email) = lower('thrifthunt3@gmail.com') limit 1),
  'My Memact App 3',
  'my-memact-app-3',
  'Uses Memact to form useful schema memory.',
  '[]'::jsonb,
  array['capture:webpage', 'schema:write', 'graph:write', 'memory:write', 'memory:read_summary']::text[],
  '2026-05-06T08:57:49.162Z'::timestamptz,
  '2026-05-06T08:57:49.162Z'::timestamptz,
  null
)
on conflict (id) do update
set
  name = excluded.name,
  slug = excluded.slug,
  description = excluded.description,
  redirect_urls = excluded.redirect_urls,
  default_scopes = excluded.default_scopes,
  updated_at = excluded.updated_at,
  revoked_at = excluded.revoked_at;

insert into public.memact_apps (
  id, owner_user_id, name, slug, description, redirect_urls, default_scopes, created_at, updated_at, revoked_at
)
values (
  'fc130b29-7362-45c8-adf7-3814582bd26e'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'My Memact App',
  'my-memact-app',
  'Uses Memact to form useful schema memory.',
  '[]'::jsonb,
  array['capture:webpage', 'schema:write', 'graph:write', 'memory:write', 'memory:read_summary']::text[],
  '2026-05-06T10:23:03.321Z'::timestamptz,
  '2026-05-06T10:23:03.321Z'::timestamptz,
  null
)
on conflict (id) do update
set
  name = excluded.name,
  slug = excluded.slug,
  description = excluded.description,
  redirect_urls = excluded.redirect_urls,
  default_scopes = excluded.default_scopes,
  updated_at = excluded.updated_at,
  revoked_at = excluded.revoked_at;

insert into public.memact_apps (
  id, owner_user_id, name, slug, description, redirect_urls, default_scopes, created_at, updated_at, revoked_at
)
values (
  'db608752-fb6c-4c77-9fd0-036cee5c02ca'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'My Memact App',
  'my-memact-app',
  'Uses Memact to form useful schema memory.',
  '[]'::jsonb,
  array['capture:webpage', 'schema:write', 'graph:write', 'memory:write', 'memory:read_summary']::text[],
  '2026-05-06T10:23:03.752Z'::timestamptz,
  '2026-05-06T10:23:03.752Z'::timestamptz,
  null
)
on conflict (id) do update
set
  name = excluded.name,
  slug = excluded.slug,
  description = excluded.description,
  redirect_urls = excluded.redirect_urls,
  default_scopes = excluded.default_scopes,
  updated_at = excluded.updated_at,
  revoked_at = excluded.revoked_at;

insert into public.memact_api_keys (
  id, app_id, owner_user_id, name, key_hash, key_prefix, scopes, created_at, last_used_at, revoked_at, first_used_notified_at
)
values (
  '103298fb-ace8-495f-bb6f-476dfca59184'::uuid,
  '5cf04c46-0bd2-4678-ad24-c66016ee8b2f'::uuid,
  (select id from auth.users where lower(email) = lower('thrifthunt3@gmail.com') limit 1),
  'Default app key',
  '376ab824c1340e8b3b96b8562c0d5161f98c09e80615c255a022bf7b216e03b3',
  'mka_XL_XgcCT',
  array['capture:webpage', 'schema:write', 'graph:write', 'memory:write', 'memory:read_summary', 'capture:media', 'capture:device', 'memory:read_graph', 'memory:read_evidence']::text[],
  '2026-05-06T04:38:22.473Z'::timestamptz,
  null,
  '2026-05-06T07:30:36.306Z'::timestamptz,
  null
)
on conflict (id) do update
set
  name = excluded.name,
  key_hash = excluded.key_hash,
  key_prefix = excluded.key_prefix,
  scopes = excluded.scopes,
  last_used_at = excluded.last_used_at,
  revoked_at = excluded.revoked_at,
  first_used_notified_at = excluded.first_used_notified_at;

insert into public.memact_api_keys (
  id, app_id, owner_user_id, name, key_hash, key_prefix, scopes, created_at, last_used_at, revoked_at, first_used_notified_at
)
values (
  'ffe04028-1a50-4e2b-b7ec-3e3f3ecbb31b'::uuid,
  'fc130b29-7362-45c8-adf7-3814582bd26e'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'Default app key',
  'c355e4dbfa37e073d7b8fbadcc8ddb0629f141d2bd2be5d307b7ffa7a40b5bfc',
  'mka_wwUwb8Tz',
  array['capture:webpage', 'schema:write', 'graph:write', 'memory:write', 'memory:read_summary', 'capture:device', 'memory:read_graph', 'memory:read_evidence', 'capture:media']::text[],
  '2026-05-06T10:26:33.868Z'::timestamptz,
  null,
  null,
  null
)
on conflict (id) do update
set
  name = excluded.name,
  key_hash = excluded.key_hash,
  key_prefix = excluded.key_prefix,
  scopes = excluded.scopes,
  last_used_at = excluded.last_used_at,
  revoked_at = excluded.revoked_at,
  first_used_notified_at = excluded.first_used_notified_at;

insert into public.memact_consents (
  id, user_id, app_id, scopes, created_at, updated_at, revoked_at
)
values (
  '7d7c79c9-11dd-4fe1-b4cc-ca7b5efb60bf'::uuid,
  (select id from auth.users where lower(email) = lower('thrifthunt3@gmail.com') limit 1),
  '5cf04c46-0bd2-4678-ad24-c66016ee8b2f'::uuid,
  array['capture:webpage', 'schema:write', 'graph:write', 'memory:write', 'memory:read_summary']::text[],
  '2026-05-06T07:30:24.781Z'::timestamptz,
  '2026-05-06T07:30:24.781Z'::timestamptz,
  null
)
on conflict (id) do update
set
  scopes = excluded.scopes,
  updated_at = excluded.updated_at,
  revoked_at = excluded.revoked_at;

insert into public.memact_consents (
  id, user_id, app_id, scopes, created_at, updated_at, revoked_at
)
values (
  '46d520d3-439f-4e60-a031-1d089d85f85c'::uuid,
  (select id from auth.users where lower(email) = lower('thrifthunt3@gmail.com') limit 1),
  '7e2c3735-3e44-4e25-be86-23d06d15884d'::uuid,
  array['capture:webpage', 'schema:write', 'graph:write', 'memory:write', 'memory:read_summary']::text[],
  '2026-05-06T08:57:54.880Z'::timestamptz,
  '2026-05-06T08:57:54.880Z'::timestamptz,
  null
)
on conflict (id) do update
set
  scopes = excluded.scopes,
  updated_at = excluded.updated_at,
  revoked_at = excluded.revoked_at;

insert into public.memact_consents (
  id, user_id, app_id, scopes, created_at, updated_at, revoked_at
)
values (
  '466fc741-ca67-41a0-9958-c1d1185c38d4'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'fc130b29-7362-45c8-adf7-3814582bd26e'::uuid,
  array['capture:webpage', 'schema:write', 'graph:write', 'memory:write', 'memory:read_summary', 'capture:device', 'memory:read_graph', 'memory:read_evidence', 'capture:media']::text[],
  '2026-05-06T10:26:31.987Z'::timestamptz,
  '2026-05-06T10:26:31.987Z'::timestamptz,
  null
)
on conflict (id) do update
set
  scopes = excluded.scopes,
  updated_at = excluded.updated_at,
  revoked_at = excluded.revoked_at;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '6c61f53b-43ba-4d76-90f9-96a371787d77'::uuid,
  (select id from auth.users where lower(email) = lower('thrifthunt3@gmail.com') limit 1),
  'user.signup',
  '{"email":"thrifthunt3@gmail.com"}'::jsonb,
  '2026-05-06T04:37:42.642Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '4bea1ab7-4d81-45e7-bcd5-6f249f9669d8'::uuid,
  (select id from auth.users where lower(email) = lower('thrifthunt3@gmail.com') limit 1),
  'app.create',
  '{"app_id":"app_5cf04c46-0bd2-4678-ad24-c66016ee8b2f"}'::jsonb,
  '2026-05-06T04:38:04.210Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'c5db4b97-fdea-408c-a41a-99891df5c897'::uuid,
  (select id from auth.users where lower(email) = lower('thrifthunt3@gmail.com') limit 1),
  'api_key.create',
  '{"app_id":"app_5cf04c46-0bd2-4678-ad24-c66016ee8b2f","key_id":"key_103298fb-ace8-495f-bb6f-476dfca59184","scopes":["capture:webpage","schema:write","graph:write","memory:write","memory:read_summary","capture:media","capture:device","memory:read_graph","memory:read_evidence"]}'::jsonb,
  '2026-05-06T04:38:22.473Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '0ff319bb-dd4e-410b-ab45-310e327e0bae'::uuid,
  (select id from auth.users where lower(email) = lower('thrifthunt3@gmail.com') limit 1),
  'user.signin',
  '{"email":"thrifthunt3@gmail.com"}'::jsonb,
  '2026-05-06T07:14:56.523Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'da8cc1f9-dcdc-4837-b273-8ab328f534cd'::uuid,
  (select id from auth.users where lower(email) = lower('thrifthunt3@gmail.com') limit 1),
  'user.signin',
  '{"email":"thrifthunt3@gmail.com"}'::jsonb,
  '2026-05-06T07:29:31.542Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '1fc06d33-3ae9-4a65-b0b4-f4ab8ceec453'::uuid,
  (select id from auth.users where lower(email) = lower('thrifthunt3@gmail.com') limit 1),
  'consent.grant',
  '{"app_id":"app_5cf04c46-0bd2-4678-ad24-c66016ee8b2f","scopes":["capture:webpage","schema:write","graph:write","memory:write","memory:read_summary"]}'::jsonb,
  '2026-05-06T07:30:24.782Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '06fa3982-3eef-4cdf-b9d1-8df562654506'::uuid,
  (select id from auth.users where lower(email) = lower('thrifthunt3@gmail.com') limit 1),
  'api_key.revoke',
  '{"key_id":"key_103298fb-ace8-495f-bb6f-476dfca59184"}'::jsonb,
  '2026-05-06T07:30:36.306Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '92935175-c063-40a1-9339-728a411d36b9'::uuid,
  (select id from auth.users where lower(email) = lower('thrifthunt3@gmail.com') limit 1),
  'app.create',
  '{"app_id":"app_1068dcc9-dcc9-4884-a88d-7e5d7c569b35"}'::jsonb,
  '2026-05-06T07:39:22.050Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '77ef8422-e063-4316-964c-7590918f6618'::uuid,
  (select id from auth.users where lower(email) = lower('thrifthunt3@gmail.com') limit 1),
  'app.create',
  '{"app_id":"app_7e2c3735-3e44-4e25-be86-23d06d15884d"}'::jsonb,
  '2026-05-06T08:57:49.162Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '5ef94f62-1b35-42a6-9eaf-b2cda21f4c2b'::uuid,
  (select id from auth.users where lower(email) = lower('thrifthunt3@gmail.com') limit 1),
  'consent.grant',
  '{"app_id":"app_7e2c3735-3e44-4e25-be86-23d06d15884d","scopes":["capture:webpage","schema:write","graph:write","memory:write","memory:read_summary"]}'::jsonb,
  '2026-05-06T08:57:54.880Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '48f5ee26-5703-41d6-b34c-8c7e558e0234'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:16:22.653Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '6b00c43f-0e11-4bbf-8776-4700e28e5425'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:16:37.705Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '563ac418-f89e-44a6-9a00-81d5e904bef2'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:16:37.742Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '06f2d6bb-c608-472c-8d5c-e4b88c87729f'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:16:40.560Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'd472c57b-9826-41ac-bda8-c221b9a49a3c'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:22:35.166Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'daf90261-aab4-4173-8e34-afc9cdc25428'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:22:43.698Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'b44589ba-04da-486f-8022-1b89a39cbe89'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:22:43.867Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'c3cef302-794c-43da-b41d-47b22b37b08c'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:22:50.554Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '1525c8a4-45d6-439e-8c22-3e86597e8d81'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:22:50.637Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '6bbea524-341b-41ef-8269-78a44a3dd6c5'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:22:50.651Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'fc7f16c7-e29d-461f-b5ac-47fab1c85dd1'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:23:03.312Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'd44b2b82-b866-46b1-98e3-e32d595b100b'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'app.create',
  '{"app_id":"app_fc130b29-7362-45c8-adf7-3814582bd26e"}'::jsonb,
  '2026-05-06T10:23:03.321Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'b3e4514b-e182-429e-aa90-19b427651f97'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:23:03.504Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '57f16de6-21a6-4bfc-89f4-cb3c4a0664bb'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:23:03.551Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'ca45f433-944a-4406-86ec-5a7c53c71213'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:23:03.583Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '2d671593-5e38-4119-b5a1-276399e167da'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:23:03.627Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'd73659b0-24f6-43c6-977e-f5ab278e27a4'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:23:03.732Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '0ea26f34-e19f-4115-9f78-b17e8be9b82c'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'app.create',
  '{"app_id":"app_db608752-fb6c-4c77-9fd0-036cee5c02ca"}'::jsonb,
  '2026-05-06T10:23:03.752Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '3afafed7-3a30-47c7-9bc7-564e65b4d6d3'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:23:03.930Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '8e93fd92-255f-4dbe-89d5-b39f6a47067e'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:23:03.958Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '81b653b1-5708-4240-9b21-cbcac06e7704'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:26:14.949Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '66e84506-58d4-4a87-89f5-239c5fd4bd8b'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:26:19.620Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'bd4aed8c-13c2-4689-b4ff-ab3ab44042d8'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:26:19.654Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'd2b37cf6-8434-4e1a-a723-3e96e3c9550c'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:26:19.698Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '0075e3e5-2968-4566-82da-04306e97a2a1'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:26:31.980Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '73117159-e9a1-4868-99ab-034da40f355b'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'consent.grant',
  '{"app_id":"app_fc130b29-7362-45c8-adf7-3814582bd26e","scopes":["capture:webpage","schema:write","graph:write","memory:write","memory:read_summary","capture:device","memory:read_graph","memory:read_evidence","capture:media"]}'::jsonb,
  '2026-05-06T10:26:31.988Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'f006d0f1-cc9e-43cb-b285-3ba71bf2ea48'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:26:32.166Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '4e6978b1-5763-4fee-8d6f-b92f04923bee'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:26:32.280Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'c360f331-9f86-47e2-bf39-b638ef1ae7bc'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:26:32.438Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'e7069de8-7560-46bf-905f-9c8dcaaa2eca'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:26:33.855Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '71a2b6b2-3458-4cd6-87d9-562b78c1bba2'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'api_key.create',
  '{"app_id":"app_fc130b29-7362-45c8-adf7-3814582bd26e","key_id":"key_ffe04028-1a50-4e2b-b7ec-3e3f3ecbb31b","scopes":["capture:webpage","schema:write","graph:write","memory:write","memory:read_summary","capture:device","memory:read_graph","memory:read_evidence","capture:media"]}'::jsonb,
  '2026-05-06T10:26:33.868Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'f4d57e17-4e69-4430-806c-215de113b8d0'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:26:34.071Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'cba93fe3-acbf-46f6-a917-9dbcc059834f'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:26:34.277Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '4d3ad73a-cfc7-4f07-bea4-5309779332f6'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:26:34.379Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'ba4aeea7-5838-4cee-89f6-e6344abd2e24'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:26:34.486Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '9a0b3f4b-0e12-4db3-bab3-2f59ec727295'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:26:35.091Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '13db26fd-55e1-4801-8eb7-88efbd37f6de'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T10:26:35.105Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'b7688829-3edd-436a-be3e-4adecf293778'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T15:41:52.262Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'b56ccdf5-f972-4cff-8547-078b7717360b'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T15:41:52.304Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '9f4b3113-4f5f-4fd5-922d-dd1f57a4d4de'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T15:46:40.990Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '12356e4d-6af9-464c-b17b-5b14244151a0'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T15:47:02.730Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '1c9369a3-08b8-4ba7-9f24-8fe5a5944b84'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T15:47:02.861Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '00ce3ce3-fb1c-4224-ab65-cd3c5b18516e'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T15:47:03.741Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '19b0354c-b5f6-4d7d-b7d5-93bb24f36116'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T15:47:04.103Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '78b2d248-760b-4653-8ee0-255da2dee73f'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T16:48:57.730Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '9d3aa674-3933-435e-b601-395c4627ec6f'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T16:48:57.964Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  '82f0a39a-37c1-413d-9ad2-0a4f5a1d5161'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T16:48:58.031Z'::timestamptz
)
on conflict (id) do nothing;

insert into public.memact_audit_log (
  id, user_id, action, details, created_at
)
values (
  'c08f664e-f0c4-414f-a205-1e6bbac48c76'::uuid,
  (select id from auth.users where lower(email) = lower('keepsloading@gmail.com') limit 1),
  'user.external_session',
  '{"provider":"github","email":"keepsloading@gmail.com"}'::jsonb,
  '2026-05-06T16:48:58.129Z'::timestamptz
)
on conflict (id) do nothing;

commit;
